### ISSUE TITLE
Memory overflow in method "telecharge"

### ISSUE THREAD

**Issue by sebastianfuehr** [Karlenkko/trajets_c-#2]
I used a .csv file with the following content to test the program:
![image](https://user-images.githubusercontent.com/40100920/71015698-59dd3600-20f4-11ea-8dbf-b2d5f351af46.png)

If I start the program now and press 7 to import all trips saved in the files, this works perfectly. But if I stop the program with 8 I get a memory overflow.

Error output is as followed:
![image](https://user-images.githubusercontent.com/40100920/71015839-8bee9800-20f4-11ea-9e58-6d96c51f0961.png)

I used valgrind with the `--track-origins=yes` and `--leak-check=full` options.

I can't find the issue, maybe you could have a look at it?

**Comment by Karlenkko** [comment]
I guess maybe try to make every tmp (in toString) an attribut of the class Traj, and finally delete it in ~Traj()
I'll try it next week, leave it for me.
If this doesn't work maybe we first use Afficher() and finish this project and take a look at it later.

**Comment by sebastianfuehr** [comment]
It seems I accidently commented a for loop in the destructor of Cata. I uncommented it and now everything works as it should.
